= Ruoli utente nel BlueXP disaster recovery
:allow-uri-read: 




=== Ruoli utente nel BlueXP disaster recovery

Il BlueXP disaster recovery ora utilizza ruoli per gestire l'accesso di ciascun utente a specifiche funzionalità e azioni.

Il servizio utilizza i seguenti ruoli specifici per il BlueXP disaster recovery.

* *Amministratore del ripristino di emergenza*: esegue qualsiasi azione nel BlueXP disaster recovery.
* *Amministratore del failover del disaster recovery*: esegue azioni di failover e migrazione nel BlueXP disaster recovery.
* *Amministratore dell'applicazione di disaster recovery*: crea e modifica piani di replica e avvia failover di prova.
* *Visualizzatore di disaster recovery*: visualizza le informazioni nel BlueXP disaster recovery, ma non può eseguire alcuna azione.


Se si fa clic sul servizio BlueXP disaster recovery e lo si configura per la prima volta, è necessario disporre dell'autorizzazione *SnapCenterAdmin* o del ruolo di *Organization Admin*.

Per ulteriori informazioni, vedere  https://docs.netapp.com/us-en/bluexp-disaster-recovery/reference/dr-reference-roles.html["Ruoli utente e autorizzazioni nel BlueXP disaster recovery"].

https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["Scopri i ruoli di accesso BlueXP per tutti i servizi"^].



=== Altri aggiornamenti nel BlueXP disaster recovery

* Rilevamento della rete migliorato
* Miglioramenti della scalabilità:
+
** Filtraggio per i metadati richiesti anziché per tutti i dettagli
** Miglioramenti della scoperta per recuperare e aggiornare più velocemente le risorse della VM
** Ottimizzazione della memoria e delle prestazioni per il recupero e l'aggiornamento dei dati
** Miglioramenti nella creazione del client e nella gestione del pool di vCenter SDK


* Gestione dei dati obsoleti alla prossima individuazione programmata o manuale:
+
** Quando una VM viene eliminata in vCenter, la BlueXP disaster recovery ora la rimuove automaticamente dal piano di replica.
** Quando un datastore o una rete vengono eliminati in vCenter, la BlueXP disaster recovery li elimina ora dal piano di replica e dal gruppo di risorse.
** Quando un cluster, un host o un data center viene eliminato in vCenter, la BlueXP disaster recovery lo elimina ora dal piano di replica e dal gruppo di risorse.


* Ora puoi accedere alla documentazione di Swagger in modalità di navigazione in incognito. Puoi accedervi da BlueXP disaster recovery tramite l'opzione Impostazioni > Documentazione API o direttamente al seguente URL in modalità di navigazione in incognito:  https://snapcenter.cloudmanager.cloud.netapp.com/api/api-doc/draas["Documentazione Swagger"^] .
* In alcune situazioni, dopo un'operazione di failback, l'iGroup veniva lasciato indietro al termine dell'operazione. Questo aggiornamento rimuove l'iGroup se è obsoleto.
* Se il nome di dominio completo NFS è stato utilizzato nel piano di replica, il BlueXP disaster recovery ora lo risolve in un indirizzo IP. Questo aggiornamento è utile se il nome di dominio completo non è risolvibile nel sito di disaster recovery.
* Miglioramenti dell'allineamento dell'interfaccia utente
* Miglioramenti del registro per acquisire i dettagli delle dimensioni di vCenter dopo la scoperta riuscita

