= Rilevamento pianificato per le VM
:allow-uri-read: 




=== Rilevamento pianificato per le VM

Il disaster recovery di BlueXP  esegue il rilevamento ogni 24 ore. Con questa release, è ora possibile personalizzare la pianificazione delle rilevazioni in modo da soddisfare le proprie esigenze e ridurre l'impatto sulle prestazioni quando necessario. Ad esempio, se si dispone di un numero elevato di macchine virtuali, è possibile impostare la pianificazione del rilevamento in modo che venga eseguita ogni 48 ore. Se si dispone di un numero limitato di macchine virtuali, è possibile impostare la pianificazione del rilevamento in modo che venga eseguita ogni 12 ore.

Se non si desidera pianificare la ricerca in wan, è possibile disattivare l'opzione di ricerca pianificata e aggiornare la ricerca manualmente in qualsiasi momento.

Per ulteriori informazioni, fare riferimento alla https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/sites-add.html["Aggiungere i siti del server vCenter"].



=== Supporto archivio dati gruppo di risorse

In precedenza, era possibile creare gruppi di risorse solo per macchine virtuali. Con questa release, puoi creare un gruppo di risorse per datastore. Quando si crea un piano di replica e si crea un gruppo di risorse per tale piano, vengono elencate tutte le macchine virtuali in un datastore. Ciò è utile se si dispone di un numero elevato di macchine virtuali e si desidera raggrupparle per datastore.

È possibile creare un gruppo di risorse con un archivio dati nei seguenti modi:

* Quando si aggiunge un gruppo di risorse tramite datastore, è possibile visualizzare un elenco di datastore. È possibile selezionare uno o più datastore per creare un gruppo di risorse.
* Quando si crea un piano di replica e si crea un gruppo di risorse all'interno del piano, è possibile visualizzare le macchine virtuali negli archivi dati.


Per ulteriori informazioni, fare riferimento a. https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Creare un piano di replica"].



=== Notifiche di prova gratuita o scadenza della licenza

Questa versione fornisce notifiche che la versione di prova gratuita scadrà tra 60 giorni per assicurarsi di avere il tempo di ottenere una licenza. Questa versione fornisce inoltre notifiche il giorno della scadenza della licenza.



=== Notifica degli aggiornamenti del servizio

Con questa versione, nella parte superiore viene visualizzato un banner per indicare che i servizi sono in fase di aggiornamento e che il servizio è in modalità di manutenzione. Il banner viene visualizzato quando il servizio è in fase di aggiornamento e scompare al termine dell'aggiornamento. Mentre è possibile continuare a lavorare nell'interfaccia utente mentre è in corso l'aggiornamento, non è possibile inoltrare nuovi lavori. I processi pianificati vengono eseguiti al termine dell'aggiornamento e il servizio torna alla modalità di produzione.
