---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-install-connector.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: 'Introduzione del disaster recovery di BlueXP tramite Amazon EVS e Amazon FSx per NetApp ONTAP. Sebbene il connettore possa essere installato in qualsiasi posizione di rete, per il disaster recovery di BlueXP consigliamo di installarlo nel sito di disaster recovery. Questo garantisce che, in caso di guasto del sito primario, l"interfaccia utente della console cloud di BlueXP continui a comunicare con il connettore e possa orchestrare il processo di ripristino all"interno di tale sito di disaster recovery.' 
---
= Installa il connettore BlueXP per il ripristino di emergenza di BlueXP
:allow-uri-read: 


[role="lead"]
Un connettore BlueXP è un software NetApp in esecuzione nel cloud o nella rete locale. Esegue le azioni necessarie a BlueXP per gestire l'infrastruttura dati. Il connettore interroga costantemente il software di disaster recovery BlueXP come livello di servizio per qualsiasi azione necessaria.

Per il servizio di disaster recovery di BlueXP, le azioni eseguite orchestrano i cluster VMware vCenter e le istanze di storage ONTAP utilizzando API native per ciascun servizio, al fine di fornire protezione alle VM di produzione in esecuzione in una posizione on-premise. Sebbene il connettore possa essere installato in qualsiasi posizione di rete, per il disaster recovery di BlueXP consigliamo di installarlo nel sito di disaster recovery. Ciò garantisce che, in caso di guasto del sito primario, l'interfaccia utente della console cloud di BlueXP continui a comunicare con il connettore e possa orchestrare il processo di ripristino all'interno di tale sito di disaster recovery.

Per utilizzare il servizio, installare il Connettore in modalità standard. Per ulteriori informazioni sui tipi di installazione del Connettore, visitare  https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Scopri le modalità di distribuzione di BlueXP | Documentazione NetApp"^] .

Sebbene il Connettore sia fondamentale per l'utilizzo del servizio, la procedura di installazione dipende dalle esigenze e dalla configurazione di rete. Fornire istruzioni specifiche per l'installazione va oltre lo scopo di queste informazioni.

Il metodo più semplice per installare un connettore con Amazon AWS è utilizzare AWS Marketplace. Per dettagli sull'installazione del connettore tramite AWS Marketplace, consultare  https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-aws-marketplace.html["Creare un connettore da AWS Marketplace | Documentazione NetApp"^] .
