---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-enable-draas.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: Introduzione al disaster recovery di BlueXP con Amazon EVS e Amazon FSx per NetApp ONTAP. Il disaster recovery di BlueXP è un prodotto con licenza che deve essere acquistato prima di poter essere utilizzato. Esistono diversi tipi di licenze e diverse modalità di acquisto. 
---
= Aggiungi il servizio di disaster recovery BlueXP al tuo account BlueXP per Amazon EVS
:allow-uri-read: 


[role="lead"]
Il disaster recovery di BlueXP è un prodotto con licenza che deve essere acquistato prima di poter essere utilizzato. Esistono diversi tipi di licenza e diverse modalità di acquisto. Una licenza dà diritto a proteggere una quantità specifica di dati per un periodo di tempo specifico.

Per ulteriori informazioni sulle licenze di ripristino di emergenza di BlueXP, vedere link:../get-started/dr-licensing.html["Imposta le licenze per il disaster recovery di BlueXP"] .



== Tipi di licenza

Esistono due tipi principali di licenza:

* NetApp offre un link:../get-started/dr-licensing.html["licenza di prova di 30 giorni"] che puoi utilizzare per valutare il disaster recovery di BlueXP utilizzando le tue risorse ONTAP e VMware. Questa licenza offre 30 giorni di utilizzo per una quantità illimitata di capacità protetta.
* Acquista una licenza di produzione se desideri la protezione DR oltre il periodo di prova di 30 giorni. Questa licenza può essere acquistata tramite i marketplace di qualsiasi partner cloud di NetApp, ma per questa guida ti consigliamo di acquistare la licenza *NetApp Intelligent Services* per il disaster recovery di BlueXP tramite Amazon AWS Marketplace. Per ulteriori informazioni sull'acquisto di una licenza tramite Amazon Marketplace, consulta link:../get-started/dr-licensing.html["Iscriviti tramite AWS Marketplace"] .




== Dimensiona le tue esigenze di capacità di disaster recovery

Prima di acquistare la licenza, è necessario comprendere quanta capacità di storage ONTAP si desidera proteggere. Uno dei vantaggi dell'utilizzo dello storage NetApp ONTAP è l'elevata efficienza con cui NetApp archivia i dati. Tutti i dati archiviati in un volume ONTAP, come un datastore VMware che ospita VM, vengono archiviati in modo altamente efficiente. ONTAP utilizza di default tre tipi di efficienza di storage durante la scrittura dei dati su storage fisico: compattazione, deduplicazione e compressione. Il risultato finale è un'efficienza di storage compresa tra 1,5:1 e 4:1, a seconda del tipo di dati archiviati. Infatti, NetApp offre un  https://www.netapp.com/media/79014-ng-937-Efficiency-Guarantee-Customer-Flyer.pdf["garanzia di efficienza di archiviazione"^] per determinati carichi di lavoro.

Questo può essere vantaggioso perché il disaster recovery di BlueXP calcola la capacità ai fini della licenza dopo l'applicazione di tutte le efficienze di storage di ONTAP. Ad esempio, supponiamo di aver effettuato il provisioning di un datastore NFS da 100 terabyte (TiB) in vCenter per ospitare 100 VM che si desidera proteggere tramite il servizio. Inoltre, supponiamo che quando i dati vengono scritti sul volume ONTAP, le tecniche di efficienza di storage applicate automaticamente comportino un consumo di soli 33 TiB per tali VM (efficienza di storage 3:1). Il disaster recovery di BlueXP deve essere concesso in licenza solo per 33 TiB, non per 100 TiB. Questo può rappresentare un vantaggio significativo per il costo totale di proprietà della soluzione di disaster recovery rispetto ad altre soluzioni di disaster recovery.

.Fasi
. Per determinare la quantità di dati consumata su ciascun volume che ospita un datastore VMware da proteggere, determinare il consumo di capacità su disco eseguendo il comando ONTAP CLI per ciascun volume:  `volume show-space -volume < _volume name_ > -vserver < _SVM name_ >` .
+
Ad esempio:

+
[listing]
----
cluster1::> volume show-space
Vserver : vm-nfs-ds1
Volume  : vol0
Feature                                Used      Used%
-----------------------------      --------     ------
User Data                           163.4MB         3%
Filesystem Metadata                   172KB         0%
Inodes                               2.93MB         0%
Snapshot Reserve                    292.9MB         5%
Total Metadata                        185KB         0%
Total Used                          459.4MB         8%
Total Physical Used                 166.4MB         3%

----
. Prendi nota del valore *Spazio Fisico Totale Utilizzato* per ciascun volume. Questo rappresenta la quantità di dati che BlueXP Disaster Recovery deve proteggere ed è il valore che utilizzerai per determinare la capacità necessaria per la licenza.

