---
sidebar: sidebar 
permalink: use/monitor-jobs.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter, monitor, bluexp 
summary: 'Il disaster recovery di NetApp BlueXP è un servizio di disaster recovery basato sul cloud che automatizza i flussi di lavoro di disaster recovery. È possibile monitorare tutti i processi di ripristino di emergenza e determinarne l"avanzamento.' 
---
= Monitorare i processi di disaster recovery di BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
È possibile monitorare tutti i processi di disaster recovery di BlueXP e verificarne l'avanzamento.

.Fasi
. Dal nav sinistro di BlueXP, seleziona *protezione* > *Disaster Recovery*.
. Dal menu superiore, selezionare *monitoraggio processi*.
. Esaminare tutti i lavori relativi alle operazioni e controllare la data e lo stato.
. Per visualizzare i dettagli di un determinato processo, selezionare la riga corrispondente.
. Per aggiornare le informazioni, selezionare *Aggiorna*.




== Annullare un lavoro

Se un lavoro è in corso o in stato di coda e non si desidera che continui, è possibile annullarlo. È possibile annullare un lavoro se è bloccato nello stesso stato e si desidera liberare l'operazione successiva nella coda. È possibile annullare un processo prima che scada.

.Fasi
. Dal nav sinistro di BlueXP, seleziona *protezione* > *Disaster Recovery*.
. Dal menu superiore, selezionare *monitoraggio processi*.
. Nella pagina monitoraggio lavoro, annotare l'ID del lavoro che si desidera annullare.
+
Il lavoro deve essere in stato "in corso" o "in coda".

. Nella colonna azioni, selezionare *Annulla lavoro*.

