---
sidebar: sidebar 
permalink: use/reports.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter, monitor, bluexp, protection, reports 
summary: 'La revisione dei report sul disaster recovery può aiutarti ad analizzare la tua preparazione al disaster recovery. I report preprogettati includono un riepilogo di failover e failback, dettagli di replica su tutti i siti e dettagli sui processi relativi all"anno precedente.' 
---
= Creare report di disaster recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
La revisione dei report sul disaster recovery può aiutarti ad analizzare la tua preparazione al disaster recovery. I report preprogettati includono un riepilogo dei failover dei test, dei dettagli del piano di replica e dei dettagli dei processi su tutti i siti all'interno di un account negli ultimi sette giorni.

È possibile scaricare i report in formato PDF, HTML o JSON.

Il collegamento Download è valido per sei ore.

.Fasi
. Dal navigatore BlueXP  sinistro, selezionare *protezione* > *Disaster Recovery* > *piani di replica*.
. Nella parte superiore della pagina, selezionare *Crea rapporto*.
. Selezionare il tipo di formato del file e il periodo di tempo negli ultimi 7 giorni.
. Selezionare *Crea*.
+

NOTE: La visualizzazione del rapporto potrebbe richiedere alcuni minuti.

. Per scaricare un report, selezionare *Scarica report* e selezionarlo nella cartella Download dell'amministratore.

