---
sidebar: sidebar 
permalink: get-started/dr-prerequisites.html 
keywords: what are bluexp disaster recovery requirements, disaster recovery prerequisites 
summary: 'Inizia il disaster recovery di BlueXP verificando il supporto per l"ambiente, l"accesso alla rete, l"accesso e il browser web.' 
---
= Prerequisiti per il disaster recovery di BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Inizia verificando la preparazione del tuo ambiente operativo, dell'accesso, dell'accesso alla rete e del browser Web.

Per utilizzare il disaster recovery di BlueXP, devi assicurarti che l'ambiente soddisfi i seguenti requisiti:

* Ambiente di lavoro VMware on-premise con storage NetApp
* Su AWS:
+
** File system Amazon FSX per NetApp ONTAP. Fare riferimento alla documentazione di Amazon FSX per ONTAP su https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started-step1.html["introduzione"^].
** Un account VMware con un Software-Defined Data Center (SDDC) su AWS, detto anche Virtual Machine Cloud. In VMware Cloud Console, utilizzare i ruoli di servizio Administrator e NSX Cloud Administrator. Utilizzare anche il proprietario dell'organizzazione per il ruolo Organizzazione. Fare riferimento a. https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/vmware-cloud-ontap.html["Virtual Machines Cloud documentazione"^].
** Collega l'SDDC con Amazon FSX per NetApp ONTAP. Fare riferimento a. https://vmc.techzone.vmware.com/fsx-guide#overview["Integrazione di VMware Cloud su AWS con Amazon FSX per NetApp ONTAP"^].


* In BlueXP:
+
** Credenziali di Amazon FSX per ONTAP e AWS aggiunte all'ambiente di lavoro BlueXP.
** È necessario configurare BlueXP Connector in BlueXP. Il connettore cloud e on-premise deve avere una connettività a vCenter con ESXis e VMware Cloud (VMC) on-premise. Ciò consente alle funzioni di backup, failover, failback e migrazione di funzionare correttamente con le funzionalità di rete e di script necessarie.
+
Il connettore BlueXP richiede le credenziali per i server vCenter di origine e di destinazione. Fare riferimento a. https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-quick-start-standard-mode.html["Avvio rapido di BlueXP"^] e. https://docs.netapp.com/us-en/cloud-manager-setup-admin/reference-networking-saas-console.html["Informazioni di rete BlueXP"^].

** Per garantire il successo dei processi di coerenza delle applicazioni, assicurarsi che siano soddisfatti i seguenti prerequisiti:
+
*** Verificare che gli strumenti VMware (o Open VM) siano in esecuzione sulle VM che verranno protette.
*** Per le macchine virtuali Windows che eseguono SQL o Oracle o entrambi, i database devono avere i relativi VSS Writer abilitati e i database devono trovarsi in uno stato stabile.
*** Per i database Oracle in esecuzione su un sistema operativo Linux, l'autenticazione utente del sistema operativo deve essere abilitata per il ruolo SYSDBA del database Oracle.





