---
sidebar: sidebar 
permalink: get-started/dr-setup.html 
keywords: bluexp, disaster recovery, aws, amazon web services, amazon fsx for netapp ontap 
summary: Per utilizzare il disaster recovery di BlueXP, esegui alcuni passaggi per configurarlo. 
---
= Configura l'infrastruttura per il disaster recovery di BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Per utilizzare il disaster recovery di BlueXP, esegui alcuni passaggi per configurarlo sia in Amazon Web Services (AWS) che in BlueXP.


TIP: Revisione link:../get-started/dr-prerequisites.html["prerequisiti"] per garantire che il tuo ambiente sia pronto.



== Preparati al disaster recovery di BlueXP

* Verificare l'ambiente di produzione.
+
** Verificare che le macchine virtuali da proteggere siano ospitate su datastore NFS (utilizzando volumi NFS ONTAP) o datastore VMFS (utilizzando LUN iSCSI NetApp).
** Assicurati di disporre delle credenziali e delle chiavi di accesso per gli array ONTAP on-premise, i vCenter e le istanze cloud VMware ospitate da AWS.


* Creare o verificare il sito di disaster recovery.
+
** Crea o verifica che il file system Amazon FSX sia pronto.
** Verifica che il peering delle macchine virtuali di origine e destinazione sia eseguito.






== Configura VMware Cloud per AWS SDDC

Configura VMware Cloud per il Software-Defined Data Center (SDDC) di AWS.

* Crea un file system Amazon FSX per ONTAP. Esegui il provisioning e configura FSX per ONTAP. Amazon FSX per NetApp ONTAP è un servizio completamente gestito che offre un file storage altamente affidabile, scalabile, dalle performance elevate e ricco di funzionalità, basato sul popolare file system ONTAP di NetApp.
* Per eseguire il provisioning e la configurazione di FSX per NetApp ONTAP, procedere come segue https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-native-overview.html["collegamento"^] https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/task-getting-started-fsx.html["Avvio rapido di Amazon FSX per NetApp ONTAP"] .
* Aggiungi Amazon FSX per NetApp ONTAP all'ambiente di lavoro e Aggiungi le credenziali AWS per FSX per ONTAP.
* In AWS, è necessario effettuare le seguenti operazioni:
+
** Implementa e configura VMware Cloud su AWS.
** Utilizzare un account VMware e effettuare il provisioning dell'SDDC. Verificare che l'SDDC sia compatibile con FSX per ONTAP.






=== Implementa il cloud VMware

https://www.vmware.com/products/vmc-on-aws.html["VMware Cloud su AWS"^] Offre un'esperienza nativa del cloud per i carichi di lavoro basati su VMware nell'ecosistema AWS. Ogni data center software-defined VMware (SDDC) viene eseguito in un Amazon Virtual Private Cloud (VPC) e fornisce uno stack VMware completo (incluso vCenter Server), il networking software-defined NSX-T, lo storage software-defined vSAN e uno o più host ESXi che forniscono risorse di calcolo e storage ai carichi di lavoro.

Per configurare un ambiente VMC su AWS, seguire questa procedura https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-setup.html["collegamento"^]. Un cluster di spie può essere utilizzato anche per il ripristino di emergenza.



== Impostare la licenza

Grazie al disaster recovery di BlueXP, puoi iscriverti a una prova gratuita di 90 giorni.

È possibile acquistare uno dei seguenti prodotti:

* Un'iscrizione pay-as-you-go (PAYGO) con il marketplace AWS
* BYOL (Bring Your Own License), ovvero un file di licenza NetApp (NLF).


Fare riferimento alla link:../get-started/dr-licensing.html["Configura le licenze di disaster recovery di BlueXP"].
