---
sidebar: sidebar 
permalink: get-started/dr-setup.html 
keywords: bluexp, disaster recovery, aws, amazon web services, amazon fsx for netapp ontap 
summary: Per utilizzare il disaster recovery di BlueXP, esegui alcuni passaggi per configurarlo. 
---
= Configura l'infrastruttura per il disaster recovery di BlueXP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Per utilizzare il disaster recovery di BlueXP, esegui alcuni passaggi per configurarlo sia in Amazon Web Services (AWS) che in BlueXP.


TIP: Revisione link:../get-started/dr-prerequisites.html["prerequisiti"] per garantire che il tuo ambiente sia pronto.



== Preparati al disaster recovery con BlueXP  per la protezione on-premise

Assicurati che siano soddisfatti i seguenti requisiti prima di impostare il disaster recovery BlueXP  per la protezione on-premise-premise:

* Storage ONTAP
+
** Assicurarsi di disporre delle credenziali ONTAP.
** Creare o verificare il sito di disaster recovery.
** Crea o verifica la tua ONTAP SVM di destinazione.
** Verifica che le SVM ONTAP di origine e destinazione siano sottoposte a peering.


* Cluster vCenter
+
** Assicurarsi che le macchine virtuali da proteggere siano ospitate su datastore NFS (utilizzando volumi NFS ONTAP) o datastore VMFS (utilizzando LUN iSCSI NetApp).
** Revisione link:../reference/vcenter-privileges.html["VCenter Privileges"] richiesta per BlueXP  DR.
** Creare un account utente per il disaster recovery (non l'account amministratore vCenter predefinito) e assegnare vCenter Privileges all'account.






== Preparati al disaster recovery di BlueXP  per la protezione on-premise nel cloud con AWS

Per configurare il disaster recovery BlueXP  per la protezione on-premise nel cloud utilizzando AWS, devi impostare quanto segue:

* Configura AWS FSX per NetApp ONTAP
* Configura VMware Cloud su AWS SDDC




=== Configura AWS FSX per NetApp ONTAP

* Crea un file system Amazon FSX per NetApp ONTAP.
+
** Esegui il provisioning e configura FSX per ONTAP. Amazon FSX per NetApp ONTAP è un servizio completamente gestito che offre un file storage altamente affidabile, scalabile, dalle performance elevate e ricco di funzionalità, costruito sul file system NetApp ONTAP.
** Seguire i passaggi in https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-native-overview.html["Report tecnico 4938: Monta Amazon FSX ONTAP come datastore NFS con VMware Cloud su AWS"^] e per eseguire il provisioning e https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/task-getting-started-fsx.html["Avvio rapido di Amazon FSX per NetApp ONTAP"] configurare FSX per ONTAP.


* Aggiungi Amazon FSX per ONTAP all'ambiente di lavoro e Aggiungi le credenziali AWS per FSX per ONTAP.
* Crea o verifica la tua SVM ONTAP di destinazione in un'istanza di AWS FSX per ONTAP.
* Configura la replica tra il cluster ONTAP on-premise di origine e l'istanza di FSX per ONTAP in BlueXP .


Per i passi dettagliati, fare riferimento alla https://docs.netapp.com/us-en/cloud-manager-fsx-ontap/use/task-creating-fsx-working-environment.html["Come impostare un ambiente di lavoro FSX per ONTAP"^] .



=== Configura VMware Cloud su AWS SDDC

https://www.vmware.com/products/vmc-on-aws.html["VMware Cloud su AWS"^] Offre un'esperienza nativa del cloud per i carichi di lavoro basati su VMware nell'ecosistema AWS. Ogni data center software-defined VMware (SDDC) viene eseguito in un Amazon Virtual Private Cloud (VPC) e fornisce uno stack VMware completo (incluso vCenter Server), il networking software-defined NSX-T, lo storage software-defined vSAN e uno o più host ESXi che forniscono risorse di calcolo e storage ai carichi di lavoro.

Per configurare un ambiente VMware Cloud su AWS, attenersi alla procedura descritta in https://docs.netapp.com/us-en/netapp-solutions/ehc/aws/aws-setup.html["Implementare e configurare l'ambiente di virtualizzazione su AWS"^]. è possibile utilizzare Un cluster pilota anche per il ripristino di emergenza.
